name: spiny-platypus

services:
  node-red:
    image: nodered/node-red:latest
    volumes:
      - ./node_red_data:/data:rw
    ports:
      - 1880:1880
    secrets:
      - node_red_credential_secret
secrets:
  node_red_credential_secret:
    file: ./secrets/node_red_credential_secret
